### ISSUE TITLE
SCanDroid misses node in callgraph

### ISSUE THREAD

**Issue by flankerhqd** [SCanDroid/SCanDroid#1]
SCanDroid is missing nodes in callgraph, which maybe related to reflection. 

I found call graphs constructed for Android program are missing nodes, e.g. if the program contains the following code:

```
TelephonyManager telephonyManager=(TelephonyManager)   
this.getSystemService(Context.TELEPHONY_SERVICE);
String imei=telephonyManager.getDeviceId();
```

or

```
TextView view = (TextView)findViewById(R.id.editText1);
String str = view.getText().toString(); 
```

**CGNodes for method calls "getDeviceId" and "getText" are missing in generated call graph pdfs!.** 

Besides, I'm experiencing the following exceptions:

```
Exception in thread "main" java.lang.IllegalArgumentException: invalid i: -1
at com.ibm.wala.util.intset.BitVectorIntSet.contains(BitVectorIntSet.java:314)
at    com.ibm.wala.ipa.cfg.AbstractInterproceduralCFG.addIntraproceduralNodesAndEdgesForCGNodeIfNeeded(AbstractInterproceduralCFG.java:149)
at com.ibm.wala.ipa.cfg.AbstractInterproceduralCFG.initForSucc(AbstractInterproceduralCFG.java:582)
at com.ibm.wala.ipa.cfg.AbstractInterproceduralCFG.getSuccNodes(AbstractInterproceduralCFG.java:607)
at com.ibm.wala.dataflow.IFDS.ICFGSupergraph.getSuccNodes(ICFGSupergraph.java:218)
at com.ibm.wala.dataflow.IFDS.ICFGSupergraph.getSuccNodes(ICFGSupergraph.java:1)
at com.ibm.wala.dataflow.IFDS.TabulationSolver.processNormal(TabulationSolver.java:341)
at com.ibm.wala.dataflow.IFDS.TabulationSolver.forwardTabulateSLRPs(TabulationSolver.java:293)
at com.ibm.wala.dataflow.IFDS.TabulationSolver.solve(TabulationSolver.java:214)
at org.scandroid.flow.FlowAnalysis.analyze(FlowAnalysis.java:209)
at org.scandroid.flow.FlowAnalysis.analyze(FlowAnalysis.java:114)
at org.scandroid.flow.FlowAnalysis.analyze(FlowAnalysis.java:89)
at org.scandroid.SeparateEntryAnalysis.analyze(SeparateEntryAnalysis.java:183)
at org.scandroid.SeparateEntryAnalysis.main(SeparateEntryAnalysis.java:143)
```

APK to reproduce the problem and outputed pdf is at https://www.dropbox.com/sh/e3c1qusn6twcn4e/ExQ3Z6OKPL?m.  The pdf is complicated but searching getDeviceId and getText returns no result.

Argument I used is 
    java -jar sap.jar --android-lib android-8.jar -c --reflection FULL MainActivity.apk

**Comment by JulianSchuette** [comment]
Have you been able to resolve the issue? I am getting the same exception with any apk I tested so far.

**Comment by alaa-alsalehi** [comment]
it takes from me too much time to figure this problem and I spend a lot of time to find a solution 
anyway add --include-library to your comand and it will work good

**Comment by flankerhqd** [comment]
Nice try.. but I've switched to other frameworks long long ago.

**Comment by alaa-alsalehi** [comment]
can you share it with us?

**Comment by flankerhqd** [comment]
Both Soot(FlowDroid) and Amandroid are being actively developed and maintained. It seems ScanDroid has been dead for a long time since the author has graduated.

**Comment by alaa-alsalehi** [comment]
Frank which one have strong String analysis?
